# Generated by Django 4.0.3 on 2022-05-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=122)),
                ('password1', models.CharField(max_length=122)),
                ('password2', models.CharField(max_length=122)),
                ('birth_date', models.DateField(max_length=122)),
            ],
        ),
    ]
