# Generated by Django 4.0.3 on 2022-05-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='year_in_school',
            field=models.CharField(choices=[('ML', 'Male'), ('FE', 'Female'), ('OT', 'Other')], default=0, max_length=2),
            preserve_default=False,
        ),
    ]
