# Generated by Django 4.0.3 on 2022-05-10 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_register_year_in_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='year_in_school',
            new_name='gender',
        ),
    ]
