# Generated by Django 4.0.3 on 2022-05-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_year_in_school_register_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='blood_group',
            field=models.CharField(choices=[(1, 'A+'), (2, 'A-'), (3, 'B+'), (4, 'B-'), (5, 'O+'), (6, 'O-'), (7, 'AB+'), (8, 'AB-')], default=0, max_length=2),
            preserve_default=False,
        ),
    ]
