# Generated by Django 4.0.3 on 2022-05-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_register_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='education',
            field=models.CharField(choices=[('PR', 'Primary'), ('UP', 'Upper_primary'), ('SP', 'Secondary'), ('HS', 'Higher Secondary'), ('BA', 'Bachelor'), ('MA', 'Master')], default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='martial_status',
            field=models.CharField(choices=[('MA', 'Married'), ('UN', 'Unmarried'), ('DI', 'Divorced')], default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='register',
            name='blood_group',
            field=models.CharField(choices=[('AP', 'A+'), ('AS', 'A-'), ('BA', 'B+'), ('BS', 'B-'), ('OP', 'O+'), ('OS', 'O-'), ('ABP', 'AB+'), ('ABS', 'AB-')], max_length=5),
        ),
        migrations.AlterField(
            model_name='register',
            name='gender',
            field=models.CharField(choices=[('ML', 'Male'), ('FE', 'Female'), ('OT', 'Other')], max_length=3),
        ),
    ]
