# Generated by Django 4.0.3 on 2022-04-27 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_question_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questiontype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionType', models.CharField(max_length=100, unique=True)),
                ('id_parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.category')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='questionType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='home.questiontype'),
        ),
    ]
