# Generated by Django 4.0.3 on 2022-04-27 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_questiontype_question_questiontype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='questionType',
        ),
    ]
